language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login --username "$USER"  --password "$PWD"

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
